[build]

publish = "dist"
edge_functions = "./edge-functions"


[[redirects]]
from = "https://session-token-splat-report.netlify.app/*"
to = "https://session-token.splat.report/:splat"
status = 301
force = true

[[redirects]]
from = "https://main--session-token-splat-report.netlify.app/*"  # [main] is a branch name
to = "https://session-token.splat.report/:splat"
status = 301
force = true


[[headers]]
  for = "_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/api/*"
  [headers.value]
    Allow- = "*"


[[edge_functions]]
path = "/api/login"
function = "login"

[[edge_functions]]
path = "/api/token"
function = "token"
